'use client';
import { useMemo, useState } from 'react';
import { allArticles, sections } from '../lib/code';

const discipline = [
 {type:'Leve', color:'slate', desc:'Conductas que alteren el orden, la disciplina o el funcionamiento sin comprometer gravemente la seguridad o el servicio.', arts:'103'},
 {type:'Grave', color:'amber', desc:'Acciones u omisiones que afecten significativamente la disciplina, cadena de mando, convivencia o ejecución del servicio.', arts:'104'},
 {type:'Gravísima', color:'red', desc:'Conductas que comprometan la seguridad, vida, integridad física, ética profesional o prestigio del Departamento.', arts:'105'},
];
const sanctions=['Amonestación verbal','Amonestación escrita','Suspensión temporal','Degradación de rango','Expulsión definitiva'];

export default function Home(){
 const [view,setView]=useState<'home'|'code'|'discipline'|'procedure'|'neutrality'>('home');
 const [query,setQuery]=useState('');
 const [section,setSection]=useState('all');
 const [selected,setSelected]=useState<number|null>(null);
 const results=useMemo(()=>allArticles.filter(a=>section==='all'||a.sectionId===section).filter(a=>!query||(`${a.n} ${a.text} ${a.tags?.join(' ')}`).toLowerCase().includes(query.toLowerCase())),[query,section]);
 const scrollTop=()=>window.scrollTo({top:0,behavior:'smooth'});
 const nav=(v:typeof view)=>{setView(v);scrollTop()};
 return <main>
  <header className="topbar"><div className="brand" onClick={()=>nav('home')}><div className="crest">LS</div><div><strong>LOS SANTOS</strong><span>FIRE DEPARTMENT</span></div></div><nav><button className={view==='home'?'active':''} onClick={()=>nav('home')}>Inicio</button><button className={view==='code'?'active':''} onClick={()=>nav('code')}>Código</button><button className={view==='discipline'?'active':''} onClick={()=>nav('discipline')}>Disciplina</button><button className={view==='procedure'?'active':''} onClick={()=>nav('procedure')}>Procedimientos</button><button className={view==='neutrality'?'active':''} onClick={()=>nav('neutrality')}>Neutralidad</button></nav><div className="status"><i/> VIGENTE</div></header>
  {view==='home' && <HomeView nav={nav} />}
  {view==='code' && <CodeView query={query} setQuery={setQuery} section={section} setSection={setSection} results={results} selected={selected} setSelected={setSelected}/>} 
  {view==='discipline' && <DisciplineView nav={nav}/>} 
  {view==='procedure' && <ProcedureView/>}
  {view==='neutrality' && <NeutralityView/>}
  <footer><div><b>LOS SANTOS FIRE DEPARTMENT</b><span>Portal Normativo Institucional</span></div><div>Versión 1.0 · Revisado en Abril 2026</div><div>Documento de referencia interna</div></footer>
 </main>
}
function HomeView({nav}:{nav:(v:any)=>void}){return <>
 <section className="hero"><div className="eyebrow">PORTAL INSTITUCIONAL · LSFD</div><h1>Normativa, disciplina<br/><em>y profesionalismo.</em></h1><p>Centro de consulta del marco disciplinario y operativo de Los Santos Fire Department.</p><div className="heroActions"><button className="primary" onClick={()=>nav('code')}>Consultar Código <span>→</span></button><button className="ghost" onClick={()=>nav('discipline')}>Régimen disciplinario</button></div><div className="heroMeta"><span><b>1.0</b> Versión vigente</span><span><b>160</b> artículos numerados*</span><span><b>VII</b> títulos</span></div></section>
 <section className="content"><div className="sectionHead"><div><div className="eyebrow">ACCESO RÁPIDO</div><h2>Marco institucional</h2></div><span className="muted">Consulta por área</span></div><div className="cards">{sections.map((s,i)=><button className="card" key={s.id} onClick={()=>nav('code')}><span className="num">0{i+1}</span><div><h3>{s.title}</h3><p>{s.subtitle}</p><small>{s.range}</small></div><span className="arrow">↗</span></button>)}</div>
 <div className="feature"><div><div className="eyebrow">PRINCIPIO INSTITUCIONAL</div><h2>La disciplina protege<br/>la operación.</h2><p>Las normas no solo establecen sanciones. Definen responsabilidades, protegen la cadena de mando y establecen criterios para actuar con seguridad y profesionalismo.</p></div><div className="featureStats"><div><b>3</b><span>niveles de falta</span></div><div><b>5</b><span>sanciones principales</span></div><div><b>20</b><span>artículos de procedimiento</span></div></div></div>
 <div className="notice"><div className="noticeIcon">!</div><div><b>Nota sobre la numeración</b><p>La versión proporcionada del Código pasa del Art. 34º al Art. 36º. El portal conserva esa numeración sin inventar un Art. 35º.</p></div></div>
 </section></>}
function CodeView({query,setQuery,section,setSection,results,selected,setSelected}:{query:string,setQuery:(v:string)=>void,section:string,setSection:(v:string)=>void,results:any[],selected:number|null,setSelected:(v:number|null)=>void}){const art=selected?allArticles.find(a=>a.n===selected):null;return <section className="content page"><div className="pageTitle"><div><div className="eyebrow">DOCUMENTO NORMATIVO</div><h1>Código Disciplinario</h1><p>Versión 1.0 · Revisado en Abril 2026 · Los Santos Fire Department</p></div><div className="docBadge">LSFD / CD-01</div></div><div className="search"><span>⌕</span><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Buscar artículo, término o contenido…"/><kbd>CTRL K</kbd></div><div className="filters"><button className={section==='all'?'selected':''} onClick={()=>setSection('all')}>Todos</button>{sections.map(s=><button key={s.id} className={section===s.id?'selected':''} onClick={()=>setSection(s.id)}>{s.title.replace('Título ','T. ')}</button>)}</div>{query||section!=='all'?<div className="results"><div className="resultCount">{results.length} resultados</div>{results.map(a=><button className="articleRow" key={a.n} onClick={()=>setSelected(a.n)}><span>ART. {a.n}º</span><div><b>{a.text.slice(0,105)}{a.text.length>105?'…':''}</b><small>{a.sectionTitle} · {a.sectionSubtitle}</small></div><i>→</i></button>)}</div>:<div className="chapterList">{sections.map(s=><div className="chapter" key={s.id}><div className="chapterHead"><div><span>{s.title}</span><h2>{s.subtitle}</h2></div><small>{s.articles.length} artículos · {s.range}</small></div><div className="articleGrid">{s.articles.map(a=><button key={a.n} onClick={()=>setSelected(a.n)}><span>ART. {a.n}º</span><p>{a.text}</p><i>↗</i></button>)}</div></div>)}</div>}{art&&<div className="modalBack" onClick={()=>setSelected(null)}><article className="modal" onClick={e=>e.stopPropagation()}><button className="close" onClick={()=>setSelected(null)}>×</button><span className="eyebrow">{art.sectionTitle} · {art.sectionSubtitle}</span><div className="articleNo">ART. {art.n}º</div><p>{art.text}</p><div className="tags">{art.tags?.map(t=><span key={t}>{t}</span>)}</div></article></div>}</section>}
function DisciplineView({nav}:{nav:(v:any)=>void}){return <section className="content page"><div className="pageTitle"><div><div className="eyebrow">TÍTULO V · ARTS. 101–120</div><h1>Régimen disciplinario</h1><p>Clasificación de faltas, circunstancias y sanciones.</p></div></div><div className="disciplineGrid">{discipline.map(d=><div className={`level ${d.color}`} key={d.type}><div className="levelTop"><span>{d.type}</span><b>Art. {d.arts}º</b></div><h2>Falta {d.type.toLowerCase()}</h2><p>{d.desc}</p></div>)}</div><div className="twoCol"><div className="panel"><div className="eyebrow">ART. 111º</div><h2>Sanciones aplicables</h2>{sanctions.map((s,i)=><div className="sanction" key={s}><span>0{i+1}</span><b>{s}</b></div>)}</div><div className="panel"><div className="eyebrow">CRITERIOS</div><h2>Proporcionalidad</h2><p>Las sanciones deben considerar la gravedad de la falta, circunstancias del hecho e historial del funcionario.</p><div className="criterion"><b>Atenuantes</b><span>Arts. 107º</span><p>Conducta anterior, colaboración, reconocimiento y reparación.</p></div><div className="criterion"><b>Agravantes</b><span>Art. 108º</span><p>Intencionalidad, premeditación, abuso de autoridad, ocultamiento y perjuicio.</p></div><button className="textBtn" onClick={()=>nav('procedure')}>Ver procedimiento disciplinario →</button></div></div></section>}
function ProcedureView(){return <section className="content page"><div className="pageTitle"><div><div className="eyebrow">TÍTULO VI · ARTS. 121–140</div><h1>Procedimiento disciplinario</h1><p>Ruta institucional desde el conocimiento del hecho hasta la resolución y apelación.</p></div></div><div className="timeline">{[['01','Inicio','Denuncia formal, informe de superior o actuación de oficio.','Art. 122º'],['02','Investigación','Designación de investigador o comisión y recopilación de antecedentes.','Arts. 123–126º'],['03','Determinación','Se establece la existencia o inexistencia de responsabilidad.','Arts. 127–128º'],['04','Resolución','La autoridad competente emite un fallo fundado.','Arts. 129–130º'],['05','Defensa y apelación','Descargos y recurso ante una instancia superior.','Arts. 131–133º'],['06','Registro','Archivo seguro y registro histórico disciplinario.','Arts. 135–140º']].map(x=><div className="step" key={x[0]}><div className="stepNo">{x[0]}</div><div><span>{x[3]}</span><h2>{x[1]}</h2><p>{x[2]}</p></div></div>)}</div><div className="due"><b>Garantías del funcionario</b><span>Debido proceso · Presunción de inocencia · Derecho a defensa · Imparcialidad</span></div></section>}
function NeutralityView(){return <section className="content page"><div className="neutralHero"><div className="eyebrow">NORMATIVA COMPLEMENTARIA · PROPUESTA</div><h1>Neutralidad institucional</h1><p>Un marco específico para proteger la independencia, imagen y representación de LSFD frente a actividades partidarias.</p></div><div className="warning"><b>Situación actual</b><p>El Código vigente contiene disposiciones relacionadas con imagen, comunicaciones, instalaciones y prestigio institucional, pero no establece una prohibición expresa y autónoma sobre la utilización partidaria de LSFD.</p></div><div className="twoCol"><div className="panel"><div className="eyebrow">ARTÍCULOS RELACIONADOS</div><h2>Marco vigente</h2>{[8,39,48,49,50].map(n=>{const a=allArticles.find(x=>x.n===n)!;return <div className="related" key={n}><b>Art. {n}º</b><p>{a.text}</p></div>})}</div><div className="panel proposal"><div className="eyebrow">PROPUESTA</div><h2>Artículo de neutralidad</h2><p><b>Neutralidad institucional.</b> LSFD mantendrá estricta neutralidad respecto de partidos políticos, organizaciones partidarias, candidaturas y actividades de carácter electoral o proselitista.</p><p>Queda prohibido utilizar el nombre, imagen, instalaciones, vehículos, uniformes, recursos, personal o representación institucional de LSFD para promover, respaldar, favorecer o asociar al Departamento con cualquier partido político, candidato u organización partidaria, salvo actividades oficiales de carácter institucional que cuenten con autorización expresa de la autoridad competente.</p><p>Ningún miembro podrá utilizar su rango, cargo, uniforme o condición de funcionario para expresar apoyo institucional a partidos políticos, candidatos u organizaciones partidarias.</p></div></div></section>}
