export type Article = { n:number; title:string; text:string; tags?:string[] };
export type Section = { id:string; title:string; subtitle:string; range:string; articles:Article[] };

const a=(n:number,text:string,tags:string[]=[]):Article=>({n,title:`Artículo ${n}º`,text,tags});

export const sections:Section[] = [
{ id:'general', title:'Título I', subtitle:'Disposiciones generales', range:'Arts. 1–20', articles:[
 a(1,'El presente Código Disciplinario tiene por objeto establecer de manera clara, formal y obligatoria las normas que regulan la conducta, disciplina, ética profesional y responsabilidades del personal de Los Santos Fire Department, de ahora en adelante reducido a LSFD, asegurando el correcto funcionamiento institucional. Su aplicación busca mantener estándares elevados de servicio, resguardando la integridad del personal y la confianza de la comunidad.', ['disciplina','institución']),
 a(2,'Las disposiciones contenidas en este Código serán aplicables a todo el personal del Departamento, sin distinción de grado, función, especialidad o antigüedad, incluyendo tanto personal operativo como administrativo, en servicio activo o en periodo de formación.', ['ámbito']),
 a(3,'Se entenderá por personal institucional a todos aquellos integrantes que formen parte de LSFD, incluyendo bomberos de línea, oficiales, chiefs, instructores, alumnos, personal en periodo de prueba y funcionarios de apoyo administrativo o técnico de carácter civil.', ['personal']),
 a(4,'La disciplina constituye el pilar fundamental del servicio bomberil, siendo indispensable para garantizar la coordinación, eficiencia y seguridad en todas las operaciones. Su observancia será obligatoria y permanente.', ['disciplina','seguridad']),
 a(5,'Todo miembro de LSFD deberá actuar conforme a los principios de honor, lealtad, integridad, respeto y vocación de servicio, orientando su conducta hacia la protección de la vida, la propiedad y el medio ambiente.', ['ética']),
 a(6,'El cumplimiento de órdenes legítimas emanadas de superiores jerárquicos será obligatorio, debiendo ejecutarse de manera oportuna, eficiente y sin cuestionamientos indebidos, salvo que dichas órdenes contravengan normas legales o de seguridad.', ['órdenes','cadena de mando']),
 a(7,'El personal deberá mantener en todo momento una conducta intachable, tanto en el ejercicio de sus funciones como fuera del servicio, evitando cualquier comportamiento que pueda afectar la imagen institucional.', ['conducta','imagen']),
 a(8,'Se prohíbe expresamente la realización de actos que menoscaben el prestigio de LSFD, incluyendo conductas públicas o privadas que generen descrédito o pérdida de confianza por parte de la comunidad.', ['imagen institucional','prestigio']),
 a(9,'Todo miembro deberá respetar estrictamente la cadena de mando, reconociendo la autoridad de sus superiores y canalizando sus acciones y comunicaciones conforme a la estructura jerárquica establecida.', ['jerarquía','cadena de mando']),
 a(10,'El personal tendrá derecho a presentar reclamos o denuncias ante situaciones de injusticia o irregularidades, debiendo hacerlo a través del conducto regular y manteniendo siempre el respeto hacia las autoridades involucradas.', ['denuncias','conducto regular']),
 a(11,'Se entenderá por conducto regular la secuencia jerárquica de mando que debe seguirse para la transmisión de solicitudes, reclamos o información, siendo su incumplimiento considerado una falta disciplinaria.', ['conducto regular']),
 a(12,'Las órdenes impartidas deberán ser claras, precisas y ejecutables, siendo responsabilidad del superior asegurar su correcta comprensión por parte del subordinado.', ['órdenes']),
 a(13,'La obediencia a órdenes no exime de responsabilidad en caso de ejecución de actos ilegales, negligentes o que comprometan la seguridad, debiendo el personal actuar con criterio profesional.', ['responsabilidad','seguridad']),
 a(14,'Todo miembro que presencie una falta grave o gravísima tendrá la obligación de informarla oportunamente a sus superiores, contribuyendo al mantenimiento de la disciplina institucional.', ['denuncia','faltas']),
 a(15,'La omisión de denuncia frente a faltas graves será considerada como una forma de complicidad, siendo sancionada conforme a la gravedad de los hechos.', ['omisión','complicidad']),
 a(16,'El servicio bomberil se regirá por principios de eficiencia, rapidez, profesionalismo y coordinación, debiendo cada miembro contribuir activamente al cumplimiento de dichos estándares.', ['servicio','profesionalismo']),
 a(17,'En toda actuación, la protección de la vida humana tendrá prioridad absoluta por sobre cualquier otro objetivo operativo o material.', ['vida','prioridad']),
 a(18,'El uso de recursos institucionales deberá limitarse estrictamente a fines del servicio, estando prohibido su uso para beneficios personales o ajenos a la función.', ['recursos']),
 a(19,'La información institucional tendrá carácter reservado cuando así se determine, debiendo resguardarse su confidencialidad para proteger la seguridad y el correcto funcionamiento de LSFD. Toda persona que requiera información, deberá ser orientada a contactar al departamento a través del aplicativo.', ['confidencialidad','información']),
 a(20,'El desconocimiento de las disposiciones contenidas en este Código no eximirá de responsabilidad disciplinaria, siendo deber de todo miembro informarse y cumplirlas.', ['cumplimiento']) ]},
{ id:'ethics', title:'Título II', subtitle:'Conducta y ética profesional', range:'Arts. 21–60', articles:[
 a(21,'Todo miembro de LSFD deberá mantener una conducta respetuosa, profesional y acorde a su investidura, tanto hacia sus superiores y compañeros como hacia la ciudadanía en general, sin distinción alguna.', ['conducta','respeto']),
 a(22,'Se prohíbe cualquier forma de discriminación basada en motivos de origen, género, condición social, religión u otros, debiendo prevalecer siempre el trato digno e igualitario.', ['igualdad']),
 a(23,'El lenguaje utilizado en el servicio deberá ser formal, respetuoso y profesional, evitando expresiones ofensivas, vulgares o inapropiadas.', ['lenguaje']),
 a(24,'Se prohíben conductas de acoso, hostigamiento o abuso de autoridad, las cuales serán consideradas faltas gravísimas dada su gravedad y efecto en la convivencia institucional.', ['acoso','abuso','gravísima']),
 a(25,'El compañerismo constituye un valor esencial, debiendo fomentarse el trabajo en equipo, la cooperación y el apoyo mutuo en todas las instancias del servicio.', ['equipo']),
 a(26,'La honestidad será un principio rector, debiendo el personal actuar siempre con veracidad, transparencia y rectitud en todas sus acciones.', ['honestidad']),
 a(27,'La falsificación de documentos, informes o declaraciones será considerada una falta gravísima, atentando contra la integridad institucional.', ['falsificación','gravísima']),
 a(28,'Se prohíbe el uso del cargo o jerarquía para obtener beneficios personales, económicos o de cualquier índole.', ['abuso de cargo']),
 a(29,'Todo acto de corrupción será sancionado con la máxima severidad, pudiendo implicar la expulsión inmediata de LSFD.', ['corrupción','expulsión']),
 a(30,'El personal deberá mantener control emocional en situaciones de alta presión, actuando con criterio, calma y profesionalismo.', ['profesionalismo']),
 a(31,'Se prohíben conductas temerarias o imprudentes que pongan en riesgo la seguridad propia o de terceros.', ['seguridad','imprudencia']),
 a(32,'Se deberá respetar en todo momento la dignidad de las víctimas, evitando tratos indignos o negligentes.', ['víctimas']),
 a(33,'La confidencialidad de la información obtenida en servicio será obligatoria, debiendo resguardarse adecuadamente.', ['confidencialidad']),
 a(34,'Se prohíbe la divulgación de información operativa sin autorización expresa de la cadena de mando. Los únicos autorizados a dar declaraciones a la prensa o a terceros, serán los oficiales del rango de Captain I en adelante.', ['prensa','comunicación']),
 a(36,'El uso de la fuerza en contra de un tercero, cuando sea necesario, deberá ser proporcional, justificado y ajustado a la legítima defensa, entendiéndose que solo se hará ante el resguardo de la vida de un tercero o la propia, aplicándose este artículo para los que intentan atentar contra su vida.', ['fuerza','legítima defensa']),
 a(37,'La negligencia en el cumplimiento del deber será considerada una falta grave o gravísima según sus consecuencias.', ['negligencia']),
 a(38,'Toda actuación deberá estar respaldada por fundamentos técnicos y operativos, conforme a la formación recibida.', ['operaciones']),
 a(39,'El personal deberá mantener en todo momento una conducta acorde a la imagen institucional.', ['imagen institucional']),
 a(40,'El incumplimiento de cualquier norma de ética tipificada en éste Código o bajo la lógica del sentido común, será obligatoriamente sancionado según las orientaciones de éste texto, debiendo consultarse los Títulos V y VI para ello.', ['ética','sanciones']),
 a(41,'Todo miembro de LSFD que no se encuentre directamente involucrado en una emergencia, procedimiento o intervención activa, deberá identificarse de manera inmediata ante cualquier requerimiento de otro funcionario, ciudadano o autoridad competente, indicando claramente su rango, apellido y número de placa. La negativa, evasión o entrega de información falsa será considerada falta grave.', ['identificación','falta grave']),
 a(42,'El personal que se encuentre fuera de servicio pero porte uniforme o cualquier distintivo institucional, estará igualmente obligado a mantener una conducta acorde a su investidura, pudiendo ser sujeto a responsabilidad disciplinaria por actos indebidos.', ['fuera de servicio','uniforme']),
 a(43,'Se prohíbe expresamente la suplantación de identidad, uso indebido de credenciales o atribución de rangos que no correspondan, considerándose dicha conducta como falta gravísima.', ['identidad','credenciales']),
 a(44,'Todo miembro deberá colaborar activamente en procedimientos internos, investigaciones o requerimientos institucionales, entregando información veraz y oportuna.', ['investigación']),
 a(45,'Se prohíbe la obstrucción de investigaciones administrativas o disciplinarias, así como la alteración, ocultamiento o destrucción de evidencia.', ['evidencia','investigación']),
 a(46,'El personal deberá mantener una actitud de respeto y subordinación ante la autoridad competente, incluso en situaciones de desacuerdo, debiendo canalizar sus objeciones por vía formal.', ['subordinación']),
 a(47,'Se prohíbe toda conducta que implique desacato, insubordinación o desafío a la autoridad, especialmente en contextos operativos o de formación.', ['insubordinación']),
 a(48,'Todo miembro deberá resguardar la imagen institucional en espacios públicos, evitando conductas que puedan generar conflicto, escándalo o desprestigio.', ['imagen','espacios públicos']),
 a(49,'El uso de medios de comunicación o difusión para emitir opiniones en nombre del Departamento sin autorización será considerado falta grave.', ['comunicación','falta grave']),
 a(50,'Se prohíbe la grabación, difusión o exposición de procedimientos operativos, víctimas o instalaciones sin autorización expresa de la cadena de mando.', ['fotografía','instalaciones','autorización']),
 a(51,'Se prohíbe a todo miembro de LSFD mantener relaciones sentimentales, afectivas o de carácter íntimo que puedan interferir directa o indirectamente con el cumplimiento de sus funciones, especialmente cuando exista subordinación jerárquica entre las partes.', ['relaciones','jerarquía']),
 a(52,'En caso de existir una relación previa entre miembros de LSFD, ésta deberá ser informada de manera inmediata a la cadena de mando mediante conducto regular, a fin de evaluar posibles conflictos de interés y adoptar medidas administrativas.', ['conflicto de interés']),
 a(53,'Toda relación afectiva que se origine entre miembros del LSFD durante el servicio activo, deberá ser informada formalmente a la autoridad competente en el más breve plazo, siendo responsabilidad de los involucrados transparentar dicha situación.', ['relaciones']),
 a(54,'La omisión en la declaración de relaciones afectivas será considerada una falta grave, especialmente cuando dicha situación derive en conflictos operativos, favoritismo o afectación del servicio.', ['falta grave','favoritismo']),
 a(55,'Se prohíbe expresamente que miembros que mantengan una relación sentimental, afectiva o familiar directa tripulen o integren de manera conjunta una misma unidad operativa, compañía o equipo de respuesta, salvo autorización excepcional fundada.', ['unidades','relaciones']),
 a(56,'La prohibición señalada en el artículo anterior se fundamenta en la necesidad de resguardar la objetividad, el criterio profesional y la toma de decisiones en situaciones críticas, evitando que vínculos personales interfieran en la seguridad del equipo.', ['objetividad','seguridad']),
 a(57,'En ningún caso un miembro podrá ejercer mando directo o indirecto sobre una persona con la que mantenga una relación afectiva o familiar, debiendo adoptarse medidas de reasignación cuando corresponda.', ['mando','conflicto']),
 a(58,'Se prohíbe cualquier manifestación pública de afecto entre miembros del LSFD mientras se encuentren en servicio, en uniforme o representando institucionalmente a la organización.', ['uniforme','conducta']),
 a(59,'Las relaciones personales no deberán traducirse en privilegios, trato preferencial, encubrimiento de faltas o alteración de evaluaciones, siendo estas conductas consideradas faltas gravísimas.', ['favoritismo','gravísima']),
 a(60,'El incumplimiento de las disposiciones relativas a relaciones interpersonales será evaluado disciplinariamente, considerando como agravante cualquier afectación a la seguridad operativa, la disciplina o la cadena de mando.', ['agravante']) ]},
{ id:'operations', title:'Título III', subtitle:'Servicio operativo y procedimientos', range:'Arts. 61–80', articles:[
 a(61,'Todo miembro deberá presentarse al servicio en condiciones físicas y mentales óptimas, garantizando su capacidad para responder adecuadamente a las exigencias operativas.', ['servicio']),
 a(62,'Se prohíbe estrictamente presentarse o permanecer en servicio bajo la influencia de alcohol, drogas o sustancias que alteren las capacidades.', ['servicio','seguridad']),
 a(63,'El uso del Equipo de Protección Personal (EPP) será obligatorio en toda intervención que lo requiera, conforme a los protocolos establecidos.', ['EPP']),
 a(64,'El incumplimiento en el uso del EPP será considerado negligencia grave, especialmente cuando comprometa la seguridad propia o de terceros.', ['EPP','negligencia']),
 a(65,'Todo procedimiento deberá ejecutarse conforme a protocolos técnicos, estándares operativos y órdenes del mando a cargo, entendiéndose el rol del Incident Commander.', ['Incident Commander','protocolos']),
 a(66,'El abandono de funciones durante una emergencia sin autorización será considerado falta gravísima.', ['abandono','gravísima']),
 a(67,'Se deberá mantener comunicación operativa constante, clara y eficiente durante toda intervención.', ['comunicación']),
 a(68,'El mando en escena deberá ser respetado sin excepción, garantizando la unidad de acción.', ['mando']),
 a(69,'Se prohíbe actuar fuera de la capacitación o certificación correspondiente, salvo en situaciones de fuerza mayor debidamente justificadas.', ['capacitación']),
 a(70,'Todo miembro deberá priorizar la seguridad del equipo y de las víctimas en cada intervención.', ['seguridad']),
 a(71,'El uso indebido de herramientas, equipos o vehículos será sancionado conforme a su gravedad.', ['equipos','vehículos']),
 a(72,'Se deberá reportar inmediatamente cualquier falla o daño en equipos o ante el desconocimiento de operación en un procedimiento, para que el mando a cargo pueda solventar las necesidades del servicio.', ['equipos','reporte']),
 a(73,'El personal deberá participar activamente en entrenamientos y capacitaciones.', ['capacitación']),
 a(74,'Se prohíbe el uso de equipos sin autorización o fuera de contexto operativo.', ['equipos']),
 a(75,'Toda intervención que implique acciones legales posteriores, deberá ser documentada conforme a los procedimientos administrativos.', ['documentación']),
 a(76,'Se deberá mantener orden y control en la escena de emergencia, según las capacitaciones y orientaciones que LSFD ha promovido y dispuesto.', ['escena']),
 a(77,'El ingreso a zonas de riesgo deberá ser autorizado por el Incident Commander en escena, siendo éste el responsable de la integridad física de su personal.', ['riesgo','Incident Commander']),
 a(78,'Se prohíbe la improvisación operativa sin evaluación de riesgos, considerando falta gravísima cualquier exposición a un riesgo innecesario.', ['riesgo','gravísima']),
 a(79,'Se deberá proteger la cadena de custodia en incidentes que lo requieran.', ['cadena de custodia']),
 a(80,'Toda negligencia operativa será objeto de investigación disciplinaria.', ['negligencia','investigación']) ]},
{ id:'uniform', title:'Título IV', subtitle:'Uniforme, equipamiento y presentación personal', range:'Arts. 81–100', articles:[
 a(81,'El uniforme institucional constituye un símbolo de autoridad y profesionalismo, debiendo portarse con respeto y corrección en todo momento.', ['uniforme']),
 a(82,'El uniforme deberá mantenerse limpio, completo y en óptimas condiciones de uso, demostrando la disciplina característica que fomenta LSFD en sus integrantes.', ['uniforme']),
 a(83,'Se prohíbe la modificación, alteración o personalización no autorizada del uniforme, dejando la libertad de vestimenta en el servicio diario, pero bajo los estándares y el marco regulatorio que rige en éste Código.', ['uniforme']),
 a(84,'Solo podrán utilizarse prendas oficialmente autorizadas por LSFD, no permitiéndose el uso de ropa civil como pantalones cortos o camisetas ajenas a LSFD ni de otras instituciones en servicio.', ['uniforme']),
 a(85,'Se prohíbe el uso de accesorios no reglamentarios que afecten la imagen institucional o la seguridad, no pudiendo ocuparse en servicio aretes, collares, pulseras y relojes de correa metálica o de cuero.', ['presentación']),
 a(86,'El personal deberá mantener una presentación personal acorde a estándares profesionales.', ['presentación']),
 a(87,'El cabello para los varones deberá ser corto y ordenado, no debiendo superar la línea mandibular. Para las mujeres, el cabello deberá mantenerse recogido en un moño o en coleta. Sin embargo, para aquellas mujeres con el pelo corto, podrán presentarse sin moño/coleta, siempre y cuando su cabello no supere su línea mandibular. En cuanto al color de cabello, siempre deberá ser de un tono natural, no permitiéndose los cabellos de colores artificiales como azul, verde, morado, etcétera.', ['cabello','presentación']),
 a(88,'El uso de vello facial quedará totalmente prohibido a nivel mandibular, dígase: barba, y/o candado. Debiendo siempre presentarse bien afeitado. Solo se autorizará el uso de bigote, siempre y cuando éste no alcance la línea mandibular y afecte el sellado de la máscara del equipo de respiración autónomo (ERA). El único personal autorizado a mantener una barba corta y ordenada, será el personal que ya no desempeñe funciones operativas.', ['barba','ERA']),
 a(89,'Los tatuajes visibles en rostro, manos y brazos no estarán permitidos mientras se esté en servicio, debiendo siempre procurar mantener la buena imagen institucional. En caso de tener los brazos tatuados, se permitirá el uso de mangas largas de color negro.', ['tatuajes']),
 a(90,'El maquillaje para las mujeres deberá ser sobrio, discreto y conforme a la formalidad institucional. Cualquier tipo de maquillaje llamativo o de colores resaltantes quedará prohibido.', ['presentación']),
 a(91,'Se prohíbe el uso del uniforme en actividades incompatibles con la función bomberil y su uso fuera de servicio deberá ser autorizado o justificado.', ['uniforme','fuera de servicio']),
 a(92,'El Equipo de Protección Personal deberá mantenerse en condiciones óptimas para su uso, debiendo hacerse el mantenimiento correspondiente después de cada incidente.', ['EPP']),
 a(93,'Se deberán realizar inspecciones periódicas del uniforme y equipamiento, quedando a disposición de los Rated Staff o superiores para inspeccionar al personal.', ['inspección']),
 a(94,'El descuido reiterado en la presentación será sancionado.', ['presentación','reiteración']),
 a(95,'Para los eventos y/o actividades formales del departamento, todo el personal deberá utilizar camisa con su correspondiente placa y rango bordado en ella, siendo más conocido como el “Uniforme Clase B | Camisa”, manteniendo pantalón liso y zapatos en buen estado. En eventos excepcionales, se dispondrá el uso del “Uniforme Clase A”.', ['Clase A','Clase B']),
 a(96,'El uniforme que se utilice deberá corresponder a la función asignada, quedando estrictamente prohibido cualquier miembro que utilice un uniforme de una división a la que no pertenece y/o se utilice un uniforme que no corresponde a las funciones diarias. Un ejemplo es que, no se podrá utilizar el uniforme de Helitac de AirOps en una atención médica regular.', ['divisiones','uniforme']),
 a(97,'Se prohíbe portar insignias o distintivos no autorizados en el uniforme, manteniendo siempre la sobriedad y el respeto pro el mismo.', ['insignias']),
 a(98,'El personal será responsable del cuidado de su equipamiento y mantener en orden su casillero ((Uniformes en sus slots)).', ['equipamiento']),
 a(99,'La pérdida de material del departamento y/o uniformes por negligencia será sancionada.', ['material','negligencia']),
 a(100,'Toda infracción a este título será considerada falta disciplinaria.', ['disciplina']) ]},
{ id:'sanctions', title:'Título V', subtitle:'Régimen disciplinario y sanciones', range:'Arts. 101–120', articles:[
 a(101,'Todo miembro de LSFD será responsable administrativa, disciplinaria y funcionalmente por sus actos u omisiones, tanto en el ejercicio de sus funciones como fuera de ellas cuando estas afecten la imagen institucional o el servicio.', ['responsabilidad']),
 a(102,'Las faltas disciplinarias serán clasificadas en leves, graves y gravísimas, considerando su naturaleza, circunstancias, reiteración y consecuencias sobre la seguridad, disciplina y prestigio institucional.', ['faltas']),
 a(103,'Se considerarán faltas leves aquellas conductas que, sin comprometer gravemente la seguridad o el servicio, alteren el orden, la disciplina o el correcto funcionamiento de las actividades institucionales.', ['leve']),
 a(104,'Se considerarán faltas graves aquellas acciones u omisiones que afecten de manera significativa la disciplina, la cadena de mando, la convivencia interna o la ejecución eficiente del servicio.', ['grave']),
 a(105,'Se considerarán faltas gravísimas aquellas que comprometan la seguridad de las personas, la vida, la integridad física, la ética profesional o el prestigio del Departamento.', ['gravísima']),
 a(106,'La reiteración de faltas, aun cuando sean de menor gravedad, constituirá un agravante, pudiendo escalar la clasificación de la falta y la sanción correspondiente.', ['agravante','reiteración']),
 a(107,'Se considerarán circunstancias atenuantes la conducta anterior irreprochable, la colaboración en la investigación, el reconocimiento de responsabilidad y la reparación del daño causado.', ['atenuantes']),
 a(108,'Se considerarán circunstancias agravantes la intencionalidad, la premeditación, el abuso de autoridad, el ocultamiento de información y el perjuicio generado al servicio o a terceros.', ['agravantes']),
 a(109,'Las sanciones disciplinarias deberán aplicarse de manera proporcional a la gravedad de la falta, considerando tanto las circunstancias del hecho como el historial del funcionario.', ['proporcionalidad']),
 a(110,'El régimen sancionatorio será progresivo, permitiendo escalar las medidas disciplinarias en función de la reiteración, gravedad y resistencia a la corrección de conductas.', ['progresividad']),
 a(111,'Las sanciones aplicables podrán consistir en amonestación verbal, amonestación escrita, suspensión temporal de funciones, degradación de rango o expulsión definitiva del departamento.', ['sanciones']),
 a(112,'Las amonestaciones verbales tendrán carácter correctivo inmediato, mientras que las escritas quedarán registradas formalmente en el historial disciplinario del funcionario.', ['amonestación']),
 a(113,'La suspensión implicará la separación temporal de funciones operativas y administrativas, pudiendo incluir restricciones de acceso a instalaciones y recursos institucionales.', ['suspensión']),
 a(114,'La degradación consistirá en la disminución de rango o funciones, aplicada en casos donde se determine pérdida de confianza o incapacidad para ejercer responsabilidades superiores.', ['degradación']),
 a(115,'La expulsión será la sanción máxima, aplicable en casos de faltas gravísimas que comprometan de forma irreparable la disciplina, seguridad o prestigio institucional.', ['expulsión']),
 a(116,'Podrán aplicarse medidas correctivas accesorias, tales como capacitaciones obligatorias, reentrenamientos o reasignaciones temporales, orientadas a corregir conductas.', ['correctivas']),
 a(117,'Toda sanción deberá estar debidamente fundada, indicando los hechos, normas infringidas y fundamentos que justifican su aplicación.', ['fundamentación']),
 a(118,'Las sanciones deberán ser registradas en los sistemas administrativos del Departamento, formando parte del historial disciplinario del funcionario.', ['registro']),
 a(119,'En casos de gravedad o riesgo para el servicio, podrá disponerse la suspensión preventiva del funcionario mientras se desarrolla la investigación correspondiente.', ['preventiva']),
 a(120,'Todo funcionario tendrá derecho a defensa, a ser informado de los cargos en su contra y a presentar antecedentes antes de la aplicación de una sanción definitiva.', ['defensa']) ]},
{ id:'procedure', title:'Título VI', subtitle:'Procedimientos disciplinarios', range:'Arts. 121–140', articles:[
 a(121,'Toda conducta que constituya una presunta falta disciplinaria dará origen a un procedimiento administrativo, el cual deberá desarrollarse conforme a los principios de legalidad, imparcialidad y debido proceso.', ['debido proceso']),
 a(122,'El procedimiento disciplinario podrá iniciarse por denuncia formal, informe de superior jerárquico o de oficio, cuando la autoridad competente tome conocimiento directo de los hechos.', ['denuncia','inicio']),
 a(123,'Una vez iniciada la investigación, se designará un funcionario o comisión investigadora, quienes deberán actuar con objetividad, independencia y apego a la normativa institucional.', ['investigación']),
 a(124,'El proceso deberá contemplar la recopilación de antecedentes, incluyendo informes, registros, evidencia material y cualquier otro elemento que permita esclarecer los hechos.', ['evidencia']),
 a(125,'Se tomarán declaraciones formales a los involucrados, testigos y cualquier persona que pueda aportar información relevante para la investigación.', ['declaraciones']),
 a(126,'La evidencia recopilada deberá ser analizada de manera técnica y objetiva, resguardando su integridad y evitando su manipulación indebida.', ['evidencia']),
 a(127,'Concluida la etapa investigativa, se determinará la existencia o inexistencia de responsabilidad disciplinaria, estableciendo los hechos de manera fundada.', ['responsabilidad']),
 a(128,'El investigador o comisión propondrá una sanción acorde a la gravedad de los hechos, considerando agravantes, atenuantes y antecedentes del funcionario.', ['sanción']),
 a(129,'La resolución final corresponderá a la autoridad competente determinada por el Profesional Standards Division, quien deberá emitir un fallo fundado y conforme a derecho.', ['PSD','resolución']),
 a(130,'Toda resolución deberá ser notificada formalmente al funcionario afectado, dejando constancia de su recepción y conocimiento.', ['notificación']),
 a(131,'El funcionario tendrá derecho a presentar descargos durante el proceso, aportando antecedentes, pruebas o argumentos en su defensa.', ['descargos','defensa']),
 a(132,'Contra la resolución sancionatoria procederá el recurso de apelación, el cual deberá presentarse dentro de los plazos establecidos por la normativa interna.', ['apelación']),
 a(133,'La apelación será conocida por una instancia superior, la cual revisará los antecedentes y podrá confirmar, modificar o revocar la resolución impugnada.', ['apelación']),
 a(134,'Todas las resoluciones deberán ser debidamente fundamentadas, indicando los hechos acreditados, normas aplicables y razones de la decisión adoptada.', ['fundamentación']),
 a(135,'Los antecedentes del procedimiento deberán ser archivados de manera ordenada y segura, garantizando su disponibilidad para futuras consultas.', ['archivo']),
 a(136,'LSFD mantendrá un registro histórico disciplinario de cada funcionario, el cual será considerado en evaluaciones y decisiones administrativas.', ['historial']),
 a(137,'Durante todo el procedimiento se deberá garantizar el respeto al debido proceso, la presunción de inocencia y el derecho a defensa del funcionario.', ['debido proceso','presunción']),
 a(138,'Se deberá evitar cualquier conflicto de interés en la designación de investigadores o autoridades resolutoras, resguardando la imparcialidad del proceso.', ['imparcialidad']),
 a(139,'La investigación podrá ser reabierta en caso de existir nuevos antecedentes relevantes que no hayan sido considerados en el proceso original.', ['reapertura']),
 a(140,'Todo procedimiento disciplinario deberá desarrollarse dentro de plazos razonables, evitando dilaciones injustificadas que afecten la eficacia del sistema disciplinario.', ['plazos']) ]},
{ id:'final', title:'Título VII', subtitle:'Disposiciones finales', range:'Arts. 141–160', articles:[
 a(141,'El presente Código Disciplinario será de cumplimiento obligatorio para todo el personal de LSFD, sin excepción de rango, función o antigüedad. Su observancia constituye un deber fundamental para garantizar el correcto funcionamiento institucional y la disciplina operativa.', ['cumplimiento']),
 a(142,'Será responsabilidad individual de cada miembro conocer, comprender y aplicar las disposiciones contenidas en este Código, no pudiendo alegarse desconocimiento como justificación ante su incumplimiento.', ['cumplimiento']),
 a(143,'La interpretación oficial de las normas contenidas en el presente Código corresponderá al Executive Staff de LSFD, sin perjuicio de las atribuciones de los mandos intermedios para su aplicación en el ámbito operativo.', ['interpretación']),
 a(144,'El presente Código podrá ser modificado, actualizado o complementado en cualquier momento, conforme a las necesidades operativas, disciplinarias o administrativas del departamento, mediante resolución formal de la autoridad competente.', ['actualización']),
 a(145,'Las disposiciones contenidas en este Código serán complementadas por reglamentos internos, órdenes generales, protocolos operativos y demás normativa institucional vigente.', ['normativa']),
 a(146,'En caso de conflicto entre normas, prevalecerán aquellas de mayor jerarquía institucional, debiendo interpretarse siempre en favor de la disciplina, la seguridad y el correcto funcionamiento del servicio.', ['jerarquía normativa']),
 a(147,'LSFD promoverá de manera permanente la mejora continua de sus procesos disciplinarios, incorporando buenas prácticas, estándares profesionales y criterios técnicos actualizados.', ['mejora']),
 a(148,'Se fomentará la formación ética y disciplinaria del personal, entendiendo que la prevención de faltas constituye un elemento esencial para el fortalecimiento institucional.', ['formación']),
 a(149,'El profesionalismo será un estándar obligatorio en todas las actuaciones del personal, debiendo reflejarse tanto en el servicio operativo como en la conducta personal.', ['profesionalismo']),
 a(150,'Se incentivará la responsabilidad individual y colectiva, promoviendo una cultura organizacional basada en la rendición de cuentas y el cumplimiento del deber.', ['responsabilidad']),
 a(151,'LSFD resguardará activamente su imagen institucional, adoptando medidas disciplinarias frente a cualquier conducta que pueda afectar la confianza pública o el prestigio de la institución.', ['imagen']),
 a(152,'Se garantizará la aplicación justa, proporcional e imparcial de las normas disciplinarias, evitando arbitrariedades y asegurando igualdad de trato entre los miembros del departamento.', ['imparcialidad']),
 a(153,'La seguridad del personal será considerada un principio fundamental, debiendo todas las normas disciplinarias interpretarse en concordancia con la protección de la vida y la integridad física.', ['seguridad']),
 a(154,'Se promoverá el trabajo en equipo como eje central del servicio, entendiendo que la cooperación y coordinación son esenciales para el éxito de las operaciones y la seguridad del personal.', ['equipo']),
 a(155,'El respeto a la jerarquía institucional será obligatorio, debiendo cada miembro reconocer y acatar la autoridad legítima de sus superiores en el marco de sus funciones.', ['jerarquía']),
 a(156,'El orden interno del departamento deberá mantenerse en todo momento, siendo responsabilidad de cada integrante contribuir activamente a la disciplina y estabilidad institucional.', ['orden']),
 a(157,'Toda desviación de las normas establecidas en el presente Código será objeto de evaluación disciplinaria, sin perjuicio de otras responsabilidades que puedan derivarse.', ['disciplina']),
 a(158,'El presente Código entrará en vigencia a contar de su publicación oficial, siendo exigible su cumplimiento desde ese momento a todo el personal del departamento.', ['vigencia']),
 a(159,'A partir de la entrada en vigencia de este Código, quedarán derogadas todas aquellas disposiciones anteriores que sean contrarias o incompatibles con el mismo.', ['derogación']),
 a(160,'El cumplimiento del presente Código será supervisado de manera permanente por la cadena de mando y las unidades competentes, quienes velarán por su correcta aplicación y observancia.', ['supervisión']) ]}
];

export const allArticles = sections.flatMap(s=>s.articles.map(a=>({...a, sectionId:s.id, sectionTitle:s.title, sectionSubtitle:s.subtitle})));
export const sectionById = (id:string)=>sections.find(s=>s.id===id);
export const articleByNumber = (n:number)=>allArticles.find(a=>a.n===n);
